abstract: mobile ip address in Japan
author: Tokuhiro Matsuno  C<< <tokuhiro __at__ mobilefactory.jp> >>
build_requires: 
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: Module::Install version 0.640
license: perl
name: Net-CIDR-MobileJP
no_index: 
  directory: 
    - inc
    - t
requires: 
  File::ShareDir: 0
  HTTP::MobileAgent: 0
  Jcode: 0
  LWP::UserAgent: 0
  Module::Pluggable::Fast: 0
  Net::CIDR::Lite: 0
  UNIVERSAL::require: 0
  YAML: 0
  version: 0
version: 0.07
