# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-CIDR-MobileJP
version:      v0.0.2
version_from: lib/Net/CIDR/MobileJP.pm
installdirs:  site
requires:
    HTTP::MobileAgent:             0
    Jcode:                         0
    LWP::UserAgent:                0
    Module::Pluggable::Fast:       0
    Net::CIDR::Lite:               0
    UNIVERSAL::require:            0
    version:                       0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
